# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, MKGV!
  displayName: 'Run a one-line script'

- script: ls -al && pwd

- script: echo "The Build id is $(Build.BuildId) and Build Number is $(Build.BuildNumber)"
  displayName: 'Displaying Build ID & Build Number'

- script: sudo apt update && sudo apt install openjdk-8-jdk && java -version
 displalyName: 'Open JDK & Checking it'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'